### ISSUE TITLE
Compiler Warnings

### ISSUE THREAD

**Issue by SeanMachen845** [logmatic/logmatic-ios#5]
I recently integrated the Logmatic pod into our swift 3 app and I am getting about 4 compiler warnings. The project still runs and logs without problem, but these warnings are rather messy. Do you guys mind taking a look into this?

**Comment by simonliotier** [comment]
I confirm the issue. The involved files are `LMLogger.h` and `LMUserDefaultsPersistence.h`. The same warning appears 4 times: 
```
Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
```

For example, in `LMLogger.h`, a warning appears on the following line:

`+ (nullable instancetype)new NS_UNAVAILABLE;`

The warning disappears if I replace it by: 

`+ (nonnull instancetype)new NS_UNAVAILABLE;`

I'm not sure why `nullable` was used in the beginning. I guess it is safe to use `nonnull`.

**Comment by gpolaert** [comment]
Hi @SeanMachen845 @simonliotier ,

Currently, my skills are very limited in iOS :( So, I trust both of you with this issue.
Do not hesitate to submit a PR. I will be very happy to merge it ;)

**Comment by simonliotier** [comment]
Hi @gpolaert,

Cool, I will submit a PR :)

**Comment by simonliotier** [comment]
Oh, I see @jeanelie already wrote this exact fix in his fork: https://github.com/jeanelie/logmatic-ios/commit/4b5b939bf538594a6a9374dadb72d31dd96bdd21

@jeanelie, would you submit the corresponding PR so @gpolaert can merge it ? :)

**Comment by jeanelie** [comment]
cc @gpolaert @simonliotier

**Comment by simonliotier** [comment]
Thanks @jeanelie!

@gpolaert, I see Jean-Élie has bumped the version in the Podspec (`1.0.2`). After the merge, would you mind pushing this new version to the master spec-repo so everyone can get this new version easily? 
Thanks!

**Comment by gpolaert** [comment]
Close #6

**Comment by gpolaert** [comment]
Thanks all

**Comment by SeanMachen845** [comment]
@gpolaert Mind making a tag and a release for this build so people can get it easily via `pod 'Logmatic', '~> 1.0.2'` instead of having to pull master?

**Comment by gpolaert** [comment]
@SeanMachen845 I've created the tag? Should I have to do something more? `pod trunk push NAME.podspec`?

**Comment by SeanMachen845** [comment]
@gpolaert I just saw the tag come up, sorry to cause concern. When I last checked the tag was not appearing on my end and `'Logmatic', '~> 1.0.2'` was not working, but it is all good now.

**Comment by SeanMachen845** [comment]
@gpolaert I just saw the tag come up, but I am still having trouble pulling from `'Logmatic', '~> 1.0.2'`. Did you update your CocoaPod as well?

**Comment by simonliotier** [comment]
@gpolaert Indeed, you have to `pod trunk push` to push this new version to the master spec-repo ([more details](https://sebastiandobrincu.com/blog/how-to-update-your-cocoapods-library-version)).

**Comment by gpolaert** [comment]
@simonliotier @SeanMachen845 it should be ok now.

**Comment by simonliotier** [comment]
It is! Thanks :)
